
resource1 = Resource.create(

  title: 'The Three-Body Problem',
  description: "Set against the backdrop of China's Cultural Revolution, a secret military project sends signals into space to establish contact with aliens. An alien civilization on the brink of destruction captures the signal and plans to invade Earth. Meanwhile, on Earth, different camps start forming, planning to either welcome the superior beings and help them take over a world seen as corrupt, or to fight against the invasion. The result is a science fiction masterpiece of enormous scope and vision.",

  content: """
    <p>During the Cultural Revolution in China, Ye Wenjie, an astrophysics alumna from Tsinghua University, witnesses her father being beaten to death by Red Guards from Tsinghua High School, while the beating was supported by Ye's mother and younger sister. Ye is officially branded a traitor and is forced to join a labor brigade in Inner Mongolia, where she befriends a government journalist who recently read Silent Spring, and who wishes to write a letter to the central government containing policy suggestions based on the book. When the central government responds, viewing the letter as an act of sedition, the journalist betrays Ye, who helped to transcribe the draft, and Ye is set to enter prison. However, she is rescued at the last minute by Yang Weining and Lei Zhicheng, two military physicists working under Red Coast (a Chinese initiative for alien communication similar to SETI) who require Ye's skills in physics. Ye discovers the possibility of amplifying outgoing radio messages by bouncing them off the sun and sends a message. Eight years later, by now in a loveless marriage with Yang, Ye receives a message from a concerned alien pacifist from the planet Trisolaris, warning her not to respond or else the inhabitants of Trisolaris will locate and invade Earth. The alien proceeds to describe Trisolaris's environmental conditions and societal history. Ye, who has come to despise humankind, responds anyway, inviting them to come to Earth to settle its problems. Ye murders her husband, Yang, along with Lei to keep the alien message a secret.</p><br/>

    <p>Some time later, with the closing of the Cultural Revolution and Ye's return to Tsinghua as a professor, Ye encounters Mike Evans, the son of the CEO of the world's largest oil company, who is also a rabid environmentalist and a believer in the idea that all species are equal. Seeing that Evans is also direly angry at humanity, Ye confides to him the events at Red Coast. Evans uses his fortune to hire men and to purchase a giant ship, which he converts into a mobile colony and listening post. Upon receiving messages from Trisolaris, thereby validating Ye's story, Evans announces the creation of the militant and semisecret Earth-Trisolaris Organization (ETO) as a fifth column for Trisolaris and appoints Ye as the leader. According to the messages, the Trisolaran invasion force has departed, but will not reach Earth for 450 years, as they are traveling at 1/100-th of lightspeed. The society attracts numerous scientists, minor government officials, and other educated people who are disappointed with world affairs. They go on to assemble a private army and even to build small nuclear weapons. However, Evans retains control of most resources and starts to alter and withhold alien messages from Ye and others. Furthermore, the society splits into factions, with the Adventists, led by Evans, seeking complete destruction of humanity by the Trisolarans, and the Redemptionists, led by Shen, seeking to help the Trisolarans to find a computational solution to the three-body problem, which plagues their home planet. A third, smaller faction, the Survivors, consisting mostly of Chinese people, intend to help the Trisolarans in exchange for their own descendants' lives while the rest of humanity dies.</p><br/>

    <p>In the present day, Wang Miao, a nanotechnology professor, is asked to work with Shi Qiang, a cunning detective, to investigate the mysterious deaths of several scientists. The two of them notice that the world's governments are communicating closely with each other, and seem to be gearing up for war. Over the next few days, Wang experiences strange hallucinatory effects. Wang sees people playing a sophisticated virtual-reality video game called Three Body (which was created by the ETO as a recruitment tool) and begins to play himself. The video game portrays a planet whose climate randomly flips between Orderly and Chaotic Eras. During Chaotic Eras, the weather oscillates unpredictably between extreme cold and extreme heat, sometimes within minutes. Once in a while, the heat rises so much that a firestorm occurs and all civilization is reduced to ashes, or the climate becomes too cold for civilization to continue developing, as heralded by the presence of \"three flying stars.\" The inhabitants (who are represented as having human bodies) struggle to develop their society and find means to predict the climate. Unlike humans, they have evolved the special ability to drain themselves of water, turning into a roll of canvas, in order to lie dormant when the Chaotic Eras occur. Characters resembling Aristotle, Mozi, Newton, and others try and fail to model the climate. Wang wins acclaim by figuring out how the climate works: (1) the planet Trisolaris has three suns, (2) the suns have different kinds of atmospheres, and when they are far away from the planet's surface, they no longer function as sources of heat and appear in the sky as stars, (3) Orderly Eras occur when two suns are far away, and Trisolaris orbits the third, (4) Chaotic Eras occur when Trisolaris is pulled by more than one sun, (5) firestorms happen when two or three suns are close to the planet's surface, (6) seeing three flying stars causes intense cold because it means all three suns are far away, and (7) if the three suns ever line up, Trisolaris will plunge into the nearest one and be consumed.</p><br/>

    <p>Wang is inducted into the ETO, and informs Shi, leading to a battle between the PLA and the society's soldiers, and the arrest of Ye. The PLA works with the Americans, led by Colonel Stanton, to ambush Evans's ship, following Shi's suggestion of cutting apart the ship and massacring the entire crew using nano-material blades, to stop them from burning their data. From the data, some new revelations emerge. For one, the aliens have extremely advanced picotechnology which allows them to create eleven-dimensional supercomputers called sophons which, when viewed in three dimensions, only occupy the volume of a proton. For another, two of these sophons have been laboriously manufactured and sent to Earth, having the power to cause hallucinations, spy on any corner of the Earth, transmit the information gathered to Trisolaris using quantum entanglement, and disrupt all of Earth's particle accelerators. The Trisolarans reason that, with particle physics being the bottleneck of science, shutting down the accelerators will paralyze Earth's technological advancement for the next 400 or more years before the Trisolarans arrive. Ye, now in custody, is allowed to visit the old Red Coast base, and reflects upon her past choices, noting that humanity from now on will never be the same.</p>

  """
)

resource2 = Resource.create(
  
  title: 'A Game of Thrones',
  description: "Long ago, in a time forgotten, a preternatural event threw the seasons out of balance. In a land where summers can last decades and winters a lifetime, trouble is brewing. The cold is returning, and in the frozen wastes to the north of Winterfell, sinister forces are massing beyond the kingdom’s protective Wall. To the south, the king’s powers are failing—his most trusted adviser dead under mysterious circumstances and his enemies emerging from the shadows of the throne. At the center of the conflict lie the Starks of Winterfell, a family as harsh and unyielding as the frozen land they were born to. Now Lord Eddard Stark is reluctantly summoned to serve as the king’s new Hand, an appointment that threatens to sunder not only his family but the kingdom itself.",
  content: """

  <p>At the beginning of the story, Lord Eddard \"Ned\" Stark executes a deserter from the Night's Watch, who has betrayed his vows and fled from the Wall. On the way back, his children adopt six direwolf pups, the animal of his sigil. There are three male and two female direwolf pups, as well as an albino runt, which aligns with his three trueborn sons, two trueborn daughters, and one bastard son. That night, Ned receives word of the death of his mentor, Lord Jon Arryn, the principal advisor to Ned's childhood friend, King Robert Baratheon. During his own visit to Ned's castle of Winterfell, Robert recruits Ned to replace Arryn as the King's Hand. Ned is reluctant, but agrees to go when he learns that Arryn's widow Lysa believes Queen Cersei Lannister and her family poisoned Arryn. Shortly thereafter, Ned's son Bran inadvertently discovers Cersei having sex with her twin brother Jaime Lannister, who throws Bran from the tower to conceal their affair.</p><br/>

  <p>Ned and his daughters Sansa and Arya depart for the royal capital of King's Landing, while his wife Catelyn, a comatose Bran, and their other sons Robb and Rickon remain at Winterfell. During the journey south, a physical altercation between Arya and Robert's son, Prince Joffrey, to whom Sansa has been betrothed, increases both the tension between the Starks and the Lannisters and the sibling rivalry between Arya and Sansa. Arya's direwolf Nymeria attacks Joffrey to protect her, and Arya chases Nymeria away to protect her from the Lannisters' wrath, therefore Sansa's direwolf Lady is executed in Nymeria's place. Upon arriving in King's Landing to take his post as Hand, Ned finds that Robert is an ineffective king whose only interests are hunting, drinking and womanizing with the realm being governed by his Small Council. Robert tells Ned of his wish to abdicate as he is bored by his kingly duties, but does not as he fears what his heir Joffrey might do as king.</p><br/>

  <p>At Winterfell, an assassin attempts to kill Bran, thwarted only by his direwolf. Catelyn departs for King's Landing to bring word of this to Ned. Shortly after that, Bran awakens as a paraplegic, with no memory of the cause of his fall. Upon Catelyn's arrival in King's Landing, she is brought to her childhood friend, Petyr \"Littlefinger\" Baelish, who identifies Tyrion Lannister, the dwarf brother of Cersei and Jaime, as the owner of the dagger used against Bran, and agrees to help Ned investigate the possibility of Lannister treason. During her return to Winterfell, Catelyn meets Tyrion by chance on the Kingsroad, arrests him, and takes him to her sister Lysa Arryn's stronghold in the Vale, where Tyrion demands trial by combat and regains his freedom when his champion, a mercenary named Bronn, is victorious. Tyrion recruits a force of tribesmen from the Vale as his private army with the aim of seeking revenge on Arryn for her mistreatment of him. In retaliation for Tyrion's abduction, his father Lord Tywin Lannister sends soldiers led by his brutish bannerman Gregor \"The Mountain\" Clegane to raid Catelyn's homeland, the Riverlands.</p><br/>

  <p>In King's Landing, Ned finds Robert's eldest brother Stannis Baratheon left the city after Jon Arryn's death for his island of Dragonstone. Ned begins to investigate into Jon Arryn's affairs, which leads him to visiting locations where Jon Arryn visited with Stannis - including places where Robert's bastard children are found. On the way back from one such place, Ned and his soldiers are waylaid by Jaime Lannister, who demands Tyrion's return, and when he does not get what he wants he orders Ned's men be killed - in the ensuing skirmish, Ned is crippled in one leg when his horse collapses on top of him. Even afterwards, Ned continues to investigate and eventually discovers that Robert's legal heirs, including Joffrey, are in fact Cersei's children by Jaime and that Jon Arryn was killed to conceal his discovery of their incest. Ned offers Cersei a chance to flee before he informs Robert, but she uses this chance to arrange Robert's death in a hunting accident.</p><br/>

  <p>Ned, made lord-regent by Robert's will, enlists Littlefinger's help to secure the loyalty and assistance of the city guards to challenge Joffrey's claim on the throne and place Stannis on the throne; but Littlefinger betrays him, resulting in Ned's arrest, and the death of his men. The spymaster on the Small Council, the eunuch Varys, accuses Ned of \"madness\" in revealing to Cersei his knowledge of her incestuous relationship. Whilst Joffrey is crowned King of the Seven Kingdoms, Ned eventually agrees to falsely confess to high treason and join the Night's Watch in exchange for Sansa and Arya's safety, but Joffrey has him beheaded anyway. Whilst Sansa is retained into custody, Arya escapes with the help of her fencing instructor, Syrio Forel, and Yoren, a recruiting agent for the Night's Watch.</p><br/>

  <p>Robb Stark has gathered an army and marched south in response to his father's arrest; and upon learning of Ned's death, attempts to raise further support from and to aid his maternal grandfather, Lord Hoster Tully. To reach the Tully lands, he agrees to a marital alliance with the notoriously unreliable House Frey, who control the intervening territory but declined to assist the Tullys despite being sworn to Riverrun. Tywin confronts a Northern-Riverlands force commanded by Roose Bolton and assigns Tyrion and his tribesmen to his vanguard out of the hope he will be killed in the coming battle. Tyrion begins a relationship with the prostitute Shae and survives the battle, which ends in a Lannister victory.</p><br/>

  <p>However, the force commanded by Bolton was merely a feint and Robb commands his main force to the relief of Riverrun. Robb proves victorious against Jaime Lannister at the Battle of the Whispering Wood, who is captured and taken prisoner, while his father Tywin decides to withdraw to the southern border of the Tully lands, sending Tyrion to King's Landing to keep Joffrey under control. When Robb elects not to ally himself with Robert's brothers Renly and Stannis, who have both made claims to the throne, the Riverlands and Northern lords hail him as \"King in the North\": his family's ancestral title.</p>

  """
)
